version: '3.4'

services:
  mongodb:
    image: mongo:latest
    container_name: entrylaunch
    ports:
      - 27017:27017
    volumes:
      - mongo_volume:/data/db
  api:
    image: apiel
    depends_on:
      - mongodb
    build: 
      context: backend
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000

  ui:
    image: uiel
    depends_on:
      - api
    build:
      context: Frontend
      dockerfile: ./Dockerfile
    ports:
      - 5173:5173

volumes:
  mongo_volume: